blueprint:
  name: Philips Hue Dimmer Switch (ZHA)
  description: >
    Control lights in a specified area using the Philips Hue Dimmer Switch (ZHA),
    replicating the default behavior of the Philips Hue app.
  domain: automation
  input:
    area:
      name: Area
      description: The area whose lights will be controlled by the dimmer switch.
      selector:
        area: {}
    dimmer_device:
      name: Dimmer Device
      description: The Philips Hue Dimmer Switch paired with ZHA.
      selector:
        device:
          integration: zha
          model: RWL021

mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input dimmer_device

variables:
  area: !input area

condition: []

action:
  - variables:
      command_type: '{{ trigger.event.data.command }}'
      args: '{{ trigger.event.data.args }}'
  - service: logbook.log
    data:
      name: Command
      message: '{{ command_type }} args: {{args}}'
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command_type == 'on_press' }}"
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
      - conditions:
          - condition: template
            value_template: "{{ command_type == 'off_press' }}"
        sequence:
          - service: light.turn_off
            target:
              area_id: "{{ area }}"
      - conditions:
          - condition: template
            value_template: >
              {{ command_type == 'step' and trigger.event.data.args[0] == 0 }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: 10
      - conditions:
          - condition: template
            value_template: >
              {{ command_type == 'step' and trigger.event.data.args[0] == 1 }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: -10
      - conditions:
          - condition: template
            value_template: >
              {{ command_type == 'on_hold'}}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              color_temp_step: 15
      - conditions:
          - condition: template
            value_template: >
              {{ command_type == 'off_hold'}}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              color_temp_step: -15
        

