blueprint:
  name: Dimmer Switch – Area Control with Scenes
  description: >
    Control lights and scenes in a specified area using the Philips Hue Dimmer Switch,
    replicating the default behavior of the Philips Hue app, including cycling scenes.
  domain: automation
  input:
    area:
      name: Area
      description: The area whose lights and scenes will be controlled by the dimmer switch.
      selector:
        area:
          multiple: false
    dimmer_device:
      name: Dimmer Device
      description: The Philips Hue Dimmer Switch paired with MQTT.
      selector:
        device:
          integration: mqtt
          entity:
            - domain: sensor
  source_url: https://github.com/thorgeir/home-assistant-automations/blob/main/blueprints/HueDimmerAreaControllBlueprint.yaml
mode: restart
max_exceeded: silent

variables:
  device_id: !input dimmer_device
  area: !input area

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/+/action"

condition:
  - condition: template
    value_template: >
      {{ trigger.topic == 'zigbee2mqtt/' ~ device_attr(device_id, 'name') ~ '/action' }}

action:
  - variables:
      payload: "{{ trigger.payload }}"
      lights: "{{ expand(area_entities(area_name(area)) | select('match', 'light')) | list }}"
      lights_on_count: "{{ expand(area_entities(area_name(area)) | select('match', 'light')) | selectattr('state', 'eq', 'on')  | list | count }}"
      primary_light: "{{ lights | list | first }}"
      scenes_count: "{{ expand(area_entities(area_name(area)) | select('match', 'scene') | list) | length }}"
      next_scene: >
        {{
          (
            (expand(area_entities(area_name(area)) | select('match', 'scene') | list) | sort(attribute='state') | selectattr('state', '==', 'unknown') | first)
            or (expand(area_entities(area_name(area)) | select('match', 'scene') | list) | sort(attribute='state') | first)
            or {'entity_id':''}
          )['entity_id'] 
        }}

  - service: logbook.log
    data:
      name: Dimmer Debug
      message: >
        Payload={{ payload }} LightsOn={{ lights_on_count }} Scenes={{ scenes_count }} NextScene={{ next_scene }}

  - choose:
      # Cycle scene on press when lights on
      - conditions:
          - condition: template
            value_template: >
              {{ payload in ['on_press_release', 'on'] and lights_on_count > 0 and scenes_count > 0 }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: "{{ next_scene }}"

      # On / Off / Toggle
      - conditions:
          - condition: template
            value_template: "{{ payload in ['on_press_release', 'on'] }}"
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
      - conditions:
          - condition: template
            value_template: "{{ payload in ['off_press_release', 'off'] }}"
        sequence:
          - service: light.turn_off
            target:
              area_id: "{{ area }}"
      - conditions:
          - condition: template
            value_template: "{{ payload == 'toggle' }}"
        sequence:
          - service: light.toggle
            target:
              area_id: "{{ area }}"

      # Brightness control
      - conditions:
          - condition: template
            value_template: >
              {{ payload in ['up_press', 'brightness_up_click'] }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: 9

      - conditions:
          - condition: template
            value_template: "{{ payload == 'up_hold' }}"
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: 22

      - conditions:
          - condition: template
            value_template: >
              {{ payload in ['down_press', 'brightness_down_click'] }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: -9

      - conditions:
          - condition: template
            value_template: "{{ payload == 'down_hold' }}"
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness_step_pct: -22

      # Hold actions for full on/off brightness extremes
      - conditions:
          - condition: template
            value_template: >
              {{ payload in ['on_hold', 'brightness_up_hold'] }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness: 255

      - conditions:
          - condition: template
            value_template: >
              {{ payload in ['off_hold', 'brightness_down_hold'] }}
        sequence:
          - service: light.turn_on
            target:
              area_id: "{{ area }}"
            data:
              brightness: 2
